name: 'seL4/Exercises'
description: |
  Runs sel4 exercises
#author: Gerwin Klein <gerwin.klein@proofcraft.systems>

inputs:
  arch:
    description: Comma separated list of architectures to filter test configs on.
    required: false
  compiler:
    description: One of `{gcc, clang}` to filter test configs on.
    required: false
  xml:
    description: sel4test xml manifest to test
    required: false
  debug:
    description: |
      Comma separated list of debug levels from `{debug, release, verification}`
      to filter test configs on. required: false
    required: false
  action_name:
    description: 'internal -- do not use'
    required: false
    default: 'sel4test-sim'

runs:
  using: 'composite'
  steps:
    - name: Build seL4 microkit
      env:
        INPUT_ARCH: ${{ inputs.ARCH }}
        INPUT_COMPILER: ${{ inputs.COMPILER }}
      shell: bash
      run: |
        echo "INPUT_ARCH=${INPUT_ARCH}"
        echo "INPUT_COMPILER=${INPUT_COMPILER}"
        echo "========================================================"
        echo "Clang in path: $(which clang)"
        echo "========================================================"

        cd ${GITHUB_WORKSPACE}
        pwd
        ls -la
        echo "========================================================"

        cd ${GITHUB_ACTION_PATH}
        pwd
        ls -la
        echo "========================================================"
        
        # Compile seL4
        cd ${GITHUB_WORKSPACE}/repo
        ${GITHUB_ACTION_PATH}/compile_kernel.sh


