# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to run on Push and Pull Request
name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:
    inputs:
      runner:
        type: string
        required: false
        default: ubuntu-latest
    secrets:
      token:
        description: 'Optional token for private repositories'
        required: false

jobs:
  check:
    name: License Check
    runs-on: ${{ inputs.runner }}
    steps:
    - uses: seL4/ci-actions/license-check@master
      with:
        token: ${{ secrets.token }}

  links:
    name: Links
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: seL4/ci-actions/link-check@master
        with:
          token: ${{ secrets.token }}
